-- Databricks notebook source
-- MAGIC %md
-- MAGIC # Video game sales 1980-2016 (vgchartz) - SQL pipeline (Databricks SQL)
-- MAGIC Generated by `scripts/build_databricks.py` from `sql/`. Executed on a serverless SQL warehouse.
-- MAGIC
-- MAGIC 1. Upload the full raw files to the Unity Catalog volume `/Volumes/workspace/da_learn_19/raw` (see `databricks/SETUP.md`).
-- MAGIC 2. Attach to a SQL warehouse (or DBR 13.3+) and *Run all*.
-- MAGIC 3. Cells: config -> 01 staging (`read_files`) -> 02 cleaning -> 03 star schema -> 04 KPIs -> 05 data quality -> visual queries.

-- COMMAND ----------

-- Config
CREATE SCHEMA IF NOT EXISTS workspace.da_learn_19;
CREATE VOLUME IF NOT EXISTS workspace.da_learn_19.raw;
USE CATALOG workspace;
USE SCHEMA da_learn_19;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 01 Staging (raw landing, no type inference for CSV; casting happens in 02)

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_vgsales AS
SELECT * EXCEPT (_rescued_data)
FROM read_files('/Volumes/workspace/da_learn_19/raw/vgsales.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_vg_ratings AS
SELECT * EXCEPT (_rescued_data)
FROM read_files('/Volumes/workspace/da_learn_19/raw/Video_Games_Sales_as_at_22_Dec_2016.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 02 Cleaning (`sql/02_cleaning.sql`)

-- COMMAND ----------

-- 02_cleaning.sql  (Spark SQL dialect; runs on DuckDB via 00_duckdb_compat.sql shims)

CREATE OR REPLACE TABLE cln_game_sales AS
WITH typed AS (
  SELECT
    TRY_CAST(trim(Rank) AS INT)                                                AS sales_rank,
    trim(Name)                                                                 AS title,
    upper(trim(Platform))                                                      AS platform,
    TRY_CAST(CASE WHEN upper(trim(Year)) IN ('N/A', 'NA', '') THEN NULL ELSE trim(Year) END AS INT) AS release_year,
    trim(Genre)                                                       AS genre,
    CASE WHEN trim(Publisher) IS NULL OR upper(trim(Publisher)) IN ('N/A', '', 'UNKNOWN') THEN 'Unknown'
         ELSE trim(Publisher) END                                              AS publisher,
    COALESCE(TRY_CAST(trim(NA_Sales) AS DOUBLE), 0)                            AS na_sales,
    COALESCE(TRY_CAST(trim(EU_Sales) AS DOUBLE), 0)                            AS eu_sales,
    COALESCE(TRY_CAST(trim(JP_Sales) AS DOUBLE), 0)                            AS jp_sales,
    COALESCE(TRY_CAST(trim(Other_Sales) AS DOUBLE), 0)                         AS other_sales,
    TRY_CAST(trim(Global_Sales) AS DOUBLE)                                     AS global_sales_reported
  FROM stg_vgsales
), dedup AS (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY lower(title), platform, COALESCE(release_year, -1) ORDER BY sales_rank) AS rn
  FROM typed
  WHERE title IS NOT NULL AND title <> '' AND platform IS NOT NULL AND global_sales_reported IS NOT NULL
)
SELECT
  sales_rank, title, platform,
  release_year,
  CASE WHEN release_year IS NULL THEN 'Unknown'
       WHEN release_year < 1990 THEN '1: 1980-89' WHEN release_year < 2000 THEN '2: 1990-99'
       WHEN release_year < 2006 THEN '3: 2000-05' WHEN release_year < 2011 THEN '4: 2006-10'
       ELSE '5: 2011-16+' END                                                  AS era,
  genre,
  publisher,
  na_sales, eu_sales, jp_sales, other_sales,
  global_sales_reported                                                        AS global_sales,
  ROUND(na_sales + eu_sales + jp_sales + other_sales, 2)                       AS regional_sum,
  CASE WHEN ABS(global_sales_reported - (na_sales + eu_sales + jp_sales + other_sales)) > 0.02 THEN 1 ELSE 0 END AS dq_global_ne_regions,
  CASE WHEN release_year IS NULL THEN 1 ELSE 0 END                             AS dq_missing_year,
  CASE WHEN release_year > 2016 THEN 1 ELSE 0 END                              AS dq_year_after_snapshot,
  CASE WHEN publisher = 'Unknown' THEN 1 ELSE 0 END                            AS dq_unknown_publisher,
  CASE WHEN global_sales_reported >= 1 THEN 1 ELSE 0 END                       AS is_million_seller,
  CASE WHEN global_sales_reported >= 10 THEN 1 ELSE 0 END                      AS is_mega_hit
FROM dedup
WHERE rn = 1;

-- COMMAND ----------

-- ---------------------------------------------------------------- critic / user scores (Metacritic, Dec-2016 snapshot)

CREATE OR REPLACE TABLE cln_vg_ratings AS
WITH typed AS (
  SELECT
    trim(Name)                                                                 AS title,
    upper(trim(Platform))                                                      AS platform,
    TRY_CAST(trim(Critic_Score) AS INT)                                        AS critic_score,
    TRY_CAST(trim(Critic_Count) AS INT)                                        AS critic_count,
    CASE WHEN lower(trim(User_Score)) = 'tbd' THEN NULL ELSE TRY_CAST(trim(User_Score) AS DOUBLE) END AS user_score_10,
    TRY_CAST(trim(User_Count) AS INT)                                          AS user_count,
    NULLIF(trim(Developer), '')                                                AS developer,
    CASE WHEN upper(trim(Rating)) = 'K-A' THEN 'E' ELSE NULLIF(upper(trim(Rating)), '') END AS esrb_rating,
    CASE WHEN lower(trim(User_Score)) = 'tbd' THEN 1 ELSE 0 END                AS dq_user_score_tbd
  FROM stg_vg_ratings
), dedup AS (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY lower(title), platform
                               ORDER BY COALESCE(critic_count, 0) DESC, COALESCE(user_count, 0) DESC) AS rn
  FROM typed WHERE title IS NOT NULL AND title <> ''
)
SELECT title, platform, critic_score, critic_count,
       ROUND(user_score_10 * 10, 1) AS user_score, user_count, developer, esrb_rating, dq_user_score_tbd,
       CASE WHEN critic_score IS NOT NULL AND (critic_score < 0 OR critic_score > 100) THEN 1 ELSE 0 END AS dq_bad_critic_score
FROM dedup
WHERE rn = 1 AND (critic_score IS NOT NULL OR user_score_10 IS NOT NULL OR esrb_rating IS NOT NULL);

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 03 Star schema (`sql/03_model.sql`)

-- COMMAND ----------

-- 03_model.sql  Star schema (Spark SQL dialect)

CREATE OR REPLACE TABLE dim_platform AS
SELECT
  CAST(ROW_NUMBER() OVER (ORDER BY platform) AS INT) AS platform_key,
  platform,
  CASE WHEN platform IN ('WII', 'NES', 'SNES', 'N64', 'GC', 'WIIU', 'GB', 'GBA', 'DS', '3DS') THEN 'Nintendo'
       WHEN platform IN ('PS', 'PS2', 'PS3', 'PS4', 'PSP', 'PSV') THEN 'Sony'
       WHEN platform IN ('XB', 'X360', 'XONE') THEN 'Microsoft'
       WHEN platform IN ('GEN', 'SAT', 'DC', 'SCD', 'GG') THEN 'Sega'
       WHEN platform = 'PC' THEN 'PC'
       ELSE 'Other' END AS platform_maker,
  CASE WHEN platform IN ('GB', 'GBA', 'DS', '3DS', 'PSP', 'PSV', 'GG', 'WS') THEN 'Handheld'
       WHEN platform = 'PC' THEN 'PC' ELSE 'Home console' END AS platform_type,
  first_year, last_year, titles
FROM (SELECT platform, MIN(release_year) AS first_year, MAX(release_year) AS last_year, COUNT(*) AS titles
      FROM cln_game_sales GROUP BY platform) p;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_genre AS
SELECT CAST(ROW_NUMBER() OVER (ORDER BY genre) AS INT) AS genre_key, genre
FROM (SELECT DISTINCT genre FROM cln_game_sales WHERE genre IS NOT NULL) g;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_publisher AS
SELECT CAST(ROW_NUMBER() OVER (ORDER BY publisher) AS INT) AS publisher_key, publisher,
       titles, CASE WHEN titles >= 100 THEN 'Major (100+ titles)' WHEN titles >= 20 THEN 'Mid (20-99)' ELSE 'Small (<20)' END AS publisher_size
FROM (SELECT publisher, COUNT(*) AS titles FROM cln_game_sales GROUP BY publisher) p;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_year AS
SELECT CAST(COALESCE(release_year, 0) AS INT) AS year_key, release_year,
       era, CASE WHEN release_year IS NULL THEN 'Unknown' ELSE concat(CAST(CAST(FLOOR(release_year / 10) * 10 AS INT) AS STRING), 's') END AS decade
FROM (SELECT DISTINCT release_year, era FROM cln_game_sales) y;

-- COMMAND ----------

CREATE OR REPLACE TABLE fact_game_sales AS
SELECT
  s.sales_rank AS game_id,
  p.platform_key, g.genre_key, pb.publisher_key, CAST(COALESCE(s.release_year, 0) AS INT) AS year_key,
  s.title,
  s.na_sales, s.eu_sales, s.jp_sales, s.other_sales, s.global_sales,
  r.critic_score, r.critic_count, r.user_score, r.user_count, r.esrb_rating, r.developer,
  CASE WHEN r.critic_score IS NULL THEN 'No score'
       WHEN r.critic_score < 50 THEN '1: <50' WHEN r.critic_score < 60 THEN '2: 50-59'
       WHEN r.critic_score < 70 THEN '3: 60-69' WHEN r.critic_score < 80 THEN '4: 70-79'
       WHEN r.critic_score < 90 THEN '5: 80-89' ELSE '6: 90+' END AS critic_band,
  CASE WHEN r.title IS NULL THEN 0 ELSE 1 END AS has_rating_match,
  s.is_million_seller, s.is_mega_hit,
  s.dq_global_ne_regions, s.dq_missing_year, s.dq_year_after_snapshot, s.dq_unknown_publisher
FROM cln_game_sales s
JOIN dim_platform p ON s.platform = p.platform
JOIN dim_genre g ON s.genre = g.genre
JOIN dim_publisher pb ON s.publisher = pb.publisher
LEFT JOIN cln_vg_ratings r ON lower(s.title) = lower(r.title) AND s.platform = r.platform;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 04 Business KPIs (`sql/04_analysis.sql`)

-- COMMAND ----------

-- 04_analysis.sql  Business KPI queries (Spark SQL dialect). Each result is materialised as an a_* table.

CREATE OR REPLACE TABLE a_kpi_headline AS
SELECT
  COUNT(*)                                                                   AS titles,
  COUNT(DISTINCT title)                                                      AS distinct_games,
  ROUND(SUM(global_sales), 2)                                                AS global_sales_m,
  ROUND(100.0 * SUM(na_sales) / SUM(na_sales + eu_sales + jp_sales + other_sales), 2)    AS na_share_pct,
  ROUND(100.0 * SUM(eu_sales) / SUM(na_sales + eu_sales + jp_sales + other_sales), 2)    AS eu_share_pct,
  ROUND(100.0 * SUM(jp_sales) / SUM(na_sales + eu_sales + jp_sales + other_sales), 2)    AS jp_share_pct,
  ROUND(100.0 * SUM(other_sales) / SUM(na_sales + eu_sales + jp_sales + other_sales), 2) AS other_share_pct,
  ROUND(AVG(global_sales), 3)                                                AS avg_sales_per_title_m,
  ROUND(percentile_approx(global_sales, 0.5), 2)                             AS median_sales_per_title_m,
  SUM(is_million_seller)                                                     AS million_sellers,
  ROUND(100.0 * SUM(is_million_seller) / COUNT(*), 2)                        AS million_seller_pct,
  COUNT(DISTINCT platform_key)                                               AS platforms,
  COUNT(DISTINCT publisher_key)                                              AS publishers,
  ROUND(100.0 * SUM(CASE WHEN critic_score IS NOT NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS critic_score_coverage_pct,
  ROUND(corr(CAST(critic_score AS DOUBLE), global_sales), 4)                 AS corr_critic_vs_sales,
  ROUND(corr(CAST(critic_score AS DOUBLE), ln(global_sales + 0.01)), 4)      AS corr_critic_vs_log_sales
FROM fact_game_sales;

-- COMMAND ----------

-- Q2 Sales by release year and region (market cycle)

CREATE OR REPLACE TABLE a_sales_by_year AS
SELECT y.release_year, COUNT(*) AS titles,
       ROUND(SUM(f.global_sales), 2) AS global_sales_m, ROUND(SUM(f.na_sales), 2) AS na_sales_m,
       ROUND(SUM(f.eu_sales), 2) AS eu_sales_m, ROUND(SUM(f.jp_sales), 2) AS jp_sales_m,
       ROUND(SUM(f.other_sales), 2) AS other_sales_m,
       ROUND(100.0 * SUM(f.jp_sales) / NULLIF(SUM(f.global_sales), 0), 2) AS jp_share_pct
FROM fact_game_sales f JOIN dim_year y ON f.year_key = y.year_key
WHERE y.release_year BETWEEN 1980 AND 2016
GROUP BY y.release_year;

-- COMMAND ----------

-- Q3 Platform league table

CREATE OR REPLACE TABLE a_platform_sales AS
SELECT p.platform, p.platform_maker, p.platform_type, p.first_year, p.last_year, COUNT(*) AS titles,
       ROUND(SUM(f.global_sales), 2) AS global_sales_m,
       ROUND(100.0 * SUM(f.global_sales) / SUM(SUM(f.global_sales)) OVER (), 2) AS share_pct,
       ROUND(AVG(f.global_sales), 3) AS avg_sales_per_title_m,
       SUM(f.is_million_seller) AS million_sellers
FROM fact_game_sales f JOIN dim_platform p ON f.platform_key = p.platform_key
GROUP BY p.platform, p.platform_maker, p.platform_type, p.first_year, p.last_year;

-- COMMAND ----------

-- Q4 Platform maker share by year (console wars)

CREATE OR REPLACE TABLE a_maker_by_year AS
SELECT y.release_year, p.platform_maker, ROUND(SUM(f.global_sales), 2) AS global_sales_m,
       ROUND(100.0 * SUM(f.global_sales) / SUM(SUM(f.global_sales)) OVER (PARTITION BY y.release_year), 2) AS share_of_year_pct
FROM fact_game_sales f JOIN dim_platform p ON f.platform_key = p.platform_key JOIN dim_year y ON f.year_key = y.year_key
WHERE y.release_year BETWEEN 1980 AND 2016
GROUP BY y.release_year, p.platform_maker;

-- COMMAND ----------

-- Q5 Genre x region (regional taste)

CREATE OR REPLACE TABLE a_genre_region AS
SELECT g.genre, COUNT(*) AS titles, ROUND(SUM(f.global_sales), 2) AS global_sales_m,
       ROUND(SUM(f.na_sales), 2) AS na_sales_m, ROUND(SUM(f.eu_sales), 2) AS eu_sales_m,
       ROUND(SUM(f.jp_sales), 2) AS jp_sales_m, ROUND(SUM(f.other_sales), 2) AS other_sales_m,
       ROUND(100.0 * SUM(f.na_sales) / SUM(SUM(f.na_sales)) OVER (), 2) AS share_of_na_pct,
       ROUND(100.0 * SUM(f.eu_sales) / SUM(SUM(f.eu_sales)) OVER (), 2) AS share_of_eu_pct,
       ROUND(100.0 * SUM(f.jp_sales) / SUM(SUM(f.jp_sales)) OVER (), 2) AS share_of_jp_pct,
       ROUND(AVG(f.global_sales), 3) AS avg_sales_per_title_m
FROM fact_game_sales f JOIN dim_genre g ON f.genre_key = g.genre_key
GROUP BY g.genre;

-- COMMAND ----------

-- Q6 Genre share of sales by era (trend)

CREATE OR REPLACE TABLE a_genre_by_era AS
SELECT y.era, g.genre, ROUND(SUM(f.global_sales), 2) AS global_sales_m,
       ROUND(100.0 * SUM(f.global_sales) / SUM(SUM(f.global_sales)) OVER (PARTITION BY y.era), 2) AS share_of_era_pct
FROM fact_game_sales f JOIN dim_genre g ON f.genre_key = g.genre_key JOIN dim_year y ON f.year_key = y.year_key
WHERE y.era <> 'Unknown'
GROUP BY y.era, g.genre;

-- COMMAND ----------

-- Q7 Publisher league table with cumulative share (concentration)

CREATE OR REPLACE TABLE a_publisher_top AS
WITH p AS (
  SELECT pb.publisher, pb.publisher_size, COUNT(*) AS titles, ROUND(SUM(f.global_sales), 2) AS global_sales_m,
         SUM(f.is_million_seller) AS million_sellers, ROUND(AVG(CAST(f.critic_score AS DOUBLE)), 1) AS avg_critic_score
  FROM fact_game_sales f JOIN dim_publisher pb ON f.publisher_key = pb.publisher_key
  GROUP BY pb.publisher, pb.publisher_size
)
SELECT ROW_NUMBER() OVER (ORDER BY global_sales_m DESC, publisher) AS publisher_rank, publisher, publisher_size, titles,
       global_sales_m, million_sellers, ROUND(100.0 * million_sellers / titles, 2) AS hit_rate_pct, avg_critic_score,
       ROUND(100.0 * global_sales_m / SUM(global_sales_m) OVER (), 2) AS share_pct,
       ROUND(100.0 * SUM(global_sales_m) OVER (ORDER BY global_sales_m DESC, publisher ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
             / SUM(global_sales_m) OVER (), 2) AS cumulative_share_pct
FROM p;

-- COMMAND ----------

-- Q8 Critic score vs sales (titles with a Metacritic score)

CREATE OR REPLACE TABLE a_critic_score_bands AS
SELECT critic_band, COUNT(*) AS titles, ROUND(AVG(global_sales), 3) AS avg_sales_m,
       ROUND(percentile_approx(global_sales, 0.5), 3) AS median_sales_m,
       ROUND(100.0 * SUM(is_million_seller) / COUNT(*), 2) AS million_seller_pct,
       ROUND(AVG(user_score), 1) AS avg_user_score
FROM fact_game_sales GROUP BY critic_band;

-- COMMAND ----------

-- Q9 Hit concentration: share of units from the top 1% / 10% of titles

CREATE OR REPLACE TABLE a_hit_concentration AS
WITH r AS (SELECT global_sales, PERCENT_RANK() OVER (ORDER BY global_sales DESC) AS pr FROM fact_game_sales)
SELECT 'top 1% of titles' AS segment, COUNT(*) AS titles, ROUND(SUM(global_sales), 2) AS global_sales_m,
       ROUND(100.0 * SUM(global_sales) / (SELECT SUM(global_sales) FROM fact_game_sales), 2) AS share_pct FROM r WHERE pr < 0.01
UNION ALL SELECT 'top 10% of titles', COUNT(*), ROUND(SUM(global_sales), 2),
       ROUND(100.0 * SUM(global_sales) / (SELECT SUM(global_sales) FROM fact_game_sales), 2) FROM r WHERE pr < 0.10
UNION ALL SELECT 'bottom 50% of titles', COUNT(*), ROUND(SUM(global_sales), 2),
       ROUND(100.0 * SUM(global_sales) / (SELECT SUM(global_sales) FROM fact_game_sales), 2) FROM r WHERE pr >= 0.50;

-- COMMAND ----------

-- Q10 ESRB rating mix (rated titles only)

CREATE OR REPLACE TABLE a_esrb_rating AS
SELECT COALESCE(esrb_rating, 'Not rated / no match') AS esrb_rating, COUNT(*) AS titles,
       ROUND(SUM(global_sales), 2) AS global_sales_m, ROUND(AVG(global_sales), 3) AS avg_sales_m,
       ROUND(100.0 * SUM(na_sales) / NULLIF(SUM(global_sales), 0), 2) AS na_share_pct
FROM fact_game_sales GROUP BY COALESCE(esrb_rating, 'Not rated / no match');

-- COMMAND ----------

-- Q11 Top 15 titles (all platforms combined)

CREATE OR REPLACE TABLE a_top_titles AS
SELECT title, COUNT(*) AS platforms, ROUND(SUM(global_sales), 2) AS global_sales_m,
       MIN(NULLIF(f.year_key, 0)) AS first_year, MAX(g.genre) AS genre
FROM fact_game_sales f JOIN dim_genre g ON f.genre_key = g.genre_key
GROUP BY title ORDER BY global_sales_m DESC LIMIT 15;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 05 Data-quality checks (`sql/05_quality_checks.sql`)

-- COMMAND ----------

-- 05_quality_checks.sql  Data-quality evidence: before/after counts, issue counts, assertions (Spark SQL dialect)

CREATE OR REPLACE TABLE dq_row_counts AS
SELECT 'game_sales' AS entity, (SELECT COUNT(*) FROM stg_vgsales) AS raw_rows,
       (SELECT COUNT(*) FROM (SELECT DISTINCT lower(trim(Name)), upper(trim(Platform)), Year FROM stg_vgsales) d) AS distinct_keys,
       (SELECT COUNT(*) FROM cln_game_sales) AS clean_rows, 'title x platform x year' AS grain
UNION ALL SELECT 'vg_ratings', (SELECT COUNT(*) FROM stg_vg_ratings),
       (SELECT COUNT(*) FROM (SELECT DISTINCT lower(trim(Name)), upper(trim(Platform)) FROM stg_vg_ratings) d),
       (SELECT COUNT(*) FROM cln_vg_ratings), 'title x platform (rows with any score/rating)'
UNION ALL SELECT 'fact_game_sales', NULL, NULL, (SELECT COUNT(*) FROM fact_game_sales), 'title x platform'
UNION ALL SELECT 'dim_platform', NULL, NULL, (SELECT COUNT(*) FROM dim_platform), 'platform'
UNION ALL SELECT 'dim_genre', NULL, NULL, (SELECT COUNT(*) FROM dim_genre), 'genre'
UNION ALL SELECT 'dim_publisher', NULL, NULL, (SELECT COUNT(*) FROM dim_publisher), 'publisher'
UNION ALL SELECT 'dim_year', NULL, NULL, (SELECT COUNT(*) FROM dim_year), 'release year (0 = unknown)';

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_null_rates AS
SELECT 'game_sales' AS entity, 'Year' AS column_name,
  (SELECT ROUND(100.0 * SUM(CASE WHEN Year IS NULL OR upper(trim(Year)) IN ('N/A', '') THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_vgsales) AS raw_null_pct,
  (SELECT ROUND(100.0 * SUM(CASE WHEN release_year IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_game_sales) AS clean_null_pct,
  'kept, year_key 0 / era Unknown' AS treatment
UNION ALL SELECT 'game_sales', 'Publisher',
  (SELECT ROUND(100.0 * SUM(CASE WHEN Publisher IS NULL OR upper(trim(Publisher)) IN ('N/A', '') THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_vgsales),
  (SELECT ROUND(100.0 * SUM(CASE WHEN publisher IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_game_sales), 'mapped to Unknown'
UNION ALL SELECT 'vg_ratings', 'Critic_Score',
  (SELECT ROUND(100.0 * SUM(CASE WHEN Critic_Score IS NULL OR trim(Critic_Score) = '' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_vg_ratings),
  (SELECT ROUND(100.0 * SUM(CASE WHEN critic_score IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_vg_ratings), 'NULL = no Metacritic score'
UNION ALL SELECT 'vg_ratings', 'User_Score',
  (SELECT ROUND(100.0 * SUM(CASE WHEN User_Score IS NULL OR trim(User_Score) = '' OR lower(trim(User_Score)) = 'tbd' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_vg_ratings),
  (SELECT ROUND(100.0 * SUM(CASE WHEN user_score IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_vg_ratings), 'tbd -> NULL, rescaled x10'
UNION ALL SELECT 'fact_game_sales', 'critic_score',
  NULL, (SELECT ROUND(100.0 * SUM(CASE WHEN critic_score IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM fact_game_sales), 'after title+platform match';

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_issues AS
SELECT 'game_sales: duplicate title x platform x year rows dropped' AS check_name,
       (SELECT COUNT(*) FROM stg_vgsales) - (SELECT COUNT(*) FROM cln_game_sales) AS affected_rows
UNION ALL SELECT 'game_sales: Year N/A (kept as Unknown)', (SELECT SUM(dq_missing_year) FROM cln_game_sales)
UNION ALL SELECT 'game_sales: Year > 2016 snapshot (kept, excluded from trends)', (SELECT SUM(dq_year_after_snapshot) FROM cln_game_sales)
UNION ALL SELECT 'game_sales: Publisher N/A or Unknown', (SELECT SUM(dq_unknown_publisher) FROM cln_game_sales)
UNION ALL SELECT 'game_sales: Global_Sales <> sum of regions by > 0.02M (rounding)', (SELECT SUM(dq_global_ne_regions) FROM cln_game_sales)
UNION ALL SELECT 'game_sales: zero-sales rows (Global_Sales = 0)', (SELECT COUNT(*) FROM cln_game_sales WHERE global_sales = 0)
UNION ALL SELECT 'vg_ratings: duplicate title x platform rows dropped',
       (SELECT COUNT(*) FROM stg_vg_ratings WHERE trim(Name) <> '') - (SELECT COUNT(*) FROM (SELECT DISTINCT lower(trim(Name)), upper(trim(Platform)) FROM stg_vg_ratings WHERE trim(Name) <> '') d)
UNION ALL SELECT 'vg_ratings: rows without any score/rating (dropped)',
       (SELECT COUNT(*) FROM (SELECT DISTINCT lower(trim(Name)), upper(trim(Platform)) FROM stg_vg_ratings WHERE trim(Name) <> '') d) - (SELECT COUNT(*) FROM cln_vg_ratings)
UNION ALL SELECT 'vg_ratings: User_Score = tbd (set NULL)', (SELECT COUNT(*) FROM stg_vg_ratings WHERE lower(trim(User_Score)) = 'tbd')
UNION ALL SELECT 'vg_ratings: ESRB K-A recoded to E', (SELECT COUNT(*) FROM stg_vg_ratings WHERE upper(trim(Rating)) = 'K-A')
UNION ALL SELECT 'fact: titles matched to a critic score', (SELECT COUNT(*) FROM fact_game_sales WHERE critic_score IS NOT NULL)
UNION ALL SELECT 'fact: titles with any ratings match', (SELECT SUM(has_rating_match) FROM fact_game_sales)
UNION ALL SELECT 'RI: fact rows lost in dim joins', (SELECT COUNT(*) FROM cln_game_sales) - (SELECT COUNT(*) FROM fact_game_sales);

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_assertions AS
WITH c AS (
  SELECT 'fact_game_sales.game_id unique' AS check_name,
         (SELECT COUNT(*) - COUNT(DISTINCT game_id) FROM fact_game_sales) AS failed_rows
  UNION ALL SELECT 'fact rows = cleaned rows (no fan-out / loss in joins)',
         (SELECT ABS((SELECT COUNT(*) FROM fact_game_sales) - (SELECT COUNT(*) FROM cln_game_sales)))
  UNION ALL SELECT 'fact.platform_key -> dim_platform', (SELECT COUNT(*) FROM fact_game_sales WHERE platform_key NOT IN (SELECT platform_key FROM dim_platform))
  UNION ALL SELECT 'fact.genre_key -> dim_genre', (SELECT COUNT(*) FROM fact_game_sales WHERE genre_key NOT IN (SELECT genre_key FROM dim_genre))
  UNION ALL SELECT 'fact.publisher_key -> dim_publisher', (SELECT COUNT(*) FROM fact_game_sales WHERE publisher_key NOT IN (SELECT publisher_key FROM dim_publisher))
  UNION ALL SELECT 'fact.year_key -> dim_year', (SELECT COUNT(*) FROM fact_game_sales WHERE year_key NOT IN (SELECT year_key FROM dim_year))
  UNION ALL SELECT 'regional sales >= 0', (SELECT COUNT(*) FROM fact_game_sales WHERE na_sales < 0 OR eu_sales < 0 OR jp_sales < 0 OR other_sales < 0)
  UNION ALL SELECT 'critic_score in 0..100', (SELECT COUNT(*) FROM fact_game_sales WHERE critic_score < 0 OR critic_score > 100)
  UNION ALL SELECT 'user_score in 0..100', (SELECT COUNT(*) FROM fact_game_sales WHERE user_score < 0 OR user_score > 100)
  UNION ALL SELECT 'global sales reconcile with regions within 1% overall',
         (SELECT CASE WHEN ABS(SUM(global_sales) - SUM(na_sales + eu_sales + jp_sales + other_sales)) <= 0.01 * SUM(global_sales) THEN 0 ELSE 1 END FROM fact_game_sales)
  UNION ALL SELECT 'platform share sums to 100%', (SELECT CASE WHEN ABS(SUM(share_pct) - 100) < 0.1 THEN 0 ELSE 1 END FROM a_platform_sales)
  UNION ALL SELECT 'dim_publisher.publisher unique', (SELECT COUNT(*) - COUNT(DISTINCT publisher) FROM dim_publisher)
)
SELECT check_name, failed_rows, CASE WHEN failed_rows = 0 THEN 'PASS' ELSE 'FAIL' END AS status FROM c;

-- COMMAND ----------

SELECT * FROM dq_row_counts ORDER BY entity;

-- COMMAND ----------

SELECT * FROM dq_assertions ORDER BY status, check_name;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Visual queries (same as the Lakeview dashboard)

-- COMMAND ----------

SELECT * FROM a_kpi_headline;

-- COMMAND ----------

-- Visualization: Units sold by release year (M) (line: x=release_year, y=global_sales_m)
SELECT release_year, global_sales_m FROM a_sales_by_year ORDER BY release_year;

-- COMMAND ----------

-- Visualization: Top 12 platforms by units sold (M) (hbar: x=platform, y=global_sales_m)
SELECT platform, global_sales_m FROM a_platform_sales ORDER BY global_sales_m DESC LIMIT 12;

-- COMMAND ----------

-- Visualization: Units sold by genre (M) (hbar: x=genre, y=global_sales_m)
SELECT genre, global_sales_m FROM a_genre_region ORDER BY global_sales_m DESC;

-- COMMAND ----------

-- Visualization: Genre share of Japanese sales (%) (hbar: x=genre, y=share_of_jp_pct)
SELECT genre, share_of_jp_pct FROM a_genre_region ORDER BY share_of_jp_pct DESC;

-- COMMAND ----------

-- Visualization: Top 10 publishers by units sold (M) (hbar: x=publisher, y=global_sales_m)
SELECT publisher, global_sales_m FROM a_publisher_top ORDER BY publisher_rank LIMIT 10;

-- COMMAND ----------

-- Visualization: Avg units per title by Metacritic score (M) (bar: x=critic_band, y=avg_sales_m)
SELECT critic_band, avg_sales_m FROM a_critic_score_bands WHERE critic_band <> 'No score' ORDER BY critic_band;
