#!/usr/bin/env python3
"""Generate the Databricks SQL notebook and Lakeview dashboard JSON from sql/02-05 + scripts/project.py.
Usage: python scripts/build_databricks.py"""
import json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import project as P

CATALOG, SCHEMA = "workspace", f"da_learn_{P.NN}"
VOLUME = f"/Volumes/{CATALOG}/{SCHEMA}/raw"
SEP = "\n\n-- COMMAND ----------\n\n"


def md(text):
    return "\n".join(["-- MAGIC %md"] + [f"-- MAGIC {l}".rstrip() for l in text.strip().splitlines()])


def statements(path):
    out, buf = [], []
    for line in path.read_text().splitlines():
        buf.append(line)
        code = line[:line.find("--")] if ("--" in line and line[:line.find("--")].count("'") % 2 == 0) else line
        if code.rstrip().endswith(";"):
            keep = [l for l in buf if not l.strip().startswith("--")]
            head = next((l for l in buf if l.strip().startswith("--")), None)
            out.append("\n".join(([head] if head else []) + keep).strip()); buf = []
    return out


def staging_sql(t, spec):
    f = f"{VOLUME}/{spec['file']}"
    if spec["format"] == "parquet":
        return f"CREATE OR REPLACE TABLE {t} AS\nSELECT * FROM read_files('{f}', format => 'parquet');"
    sch = f",\n  schema => '{', '.join(c + ' STRING' for c in spec['columns'])}'" if spec.get("columns") else ""
    sel = "*" if spec.get("columns") else "* EXCEPT (_rescued_data)"
    return (f"CREATE OR REPLACE TABLE {t} AS\nSELECT {sel}\nFROM read_files('{f}',\n"
            f"  format => 'csv', header => true, multiLine => true, escape => '\"', inferColumnTypes => false{sch});")


def notebook():
    cells = ["-- Databricks notebook source\n" + md(f"""
# {P.DASH_TITLE} - SQL pipeline (Databricks SQL)
Generated by `scripts/build_databricks.py` from `sql/`. Executed on a serverless SQL warehouse.

1. Upload the full raw files to the Unity Catalog volume `{VOLUME}` (see `databricks/SETUP.md`).
2. Attach to a SQL warehouse (or DBR 13.3+) and *Run all*.
3. Cells: config -> 01 staging (`read_files`) -> 02 cleaning -> 03 star schema -> 04 KPIs -> 05 data quality -> visual queries.""")]
    cells.append(f"-- Config\nCREATE SCHEMA IF NOT EXISTS {CATALOG}.{SCHEMA};\nCREATE VOLUME IF NOT EXISTS {CATALOG}.{SCHEMA}.raw;\nUSE CATALOG {CATALOG};\nUSE SCHEMA {SCHEMA};")
    cells.append(md("## 01 Staging (raw landing, no type inference for CSV; casting happens in 02)"))
    cells += [staging_sql(t, s) for t, s in P.RAW.items()]
    for f, title in [("02_cleaning.sql", "02 Cleaning"), ("03_model.sql", "03 Star schema"),
                     ("04_analysis.sql", "04 Business KPIs"), ("05_quality_checks.sql", "05 Data-quality checks")]:
        cells.append(md(f"## {title} (`sql/{f}`)"))
        cells += statements(ROOT / "sql" / f)
    cells.append("SELECT * FROM dq_row_counts ORDER BY entity;")
    cells.append("SELECT * FROM dq_assertions ORDER BY status, check_name;")
    cells.append(md("## Visual queries (same as the Lakeview dashboard)"))
    cells.append("SELECT * FROM a_kpi_headline;")
    for v in P.VIZ:
        cells.append(f"-- Visualization: {v['title']} ({v['kind']}: x={v['x']}, y={v['y']})\n{v['sql'].format(S='')};")
    return SEP.join(cells) + "\n"


def widget(name, ds, fields, spec, pos):
    return {"widget": {"name": name, "queries": [{"name": "main_query", "query": {"datasetName": ds, "fields": fields, "disaggregated": True}}], "spec": spec}, "position": pos}


FMT = {"pct": {"type": "number-percent", "decimalPlaces": {"type": "max", "places": 1}},
       "num": {"type": "number", "abbreviation": "compact", "decimalPlaces": {"type": "max", "places": 1}},
       "usd": {"type": "number-currency", "currencyCode": P.CURRENCY, "abbreviation": "compact", "decimalPlaces": {"type": "max", "places": 1}}}


def viz_widget(v, pos):
    xs = {"line": v.get("xscale", "categorical")}.get(v["kind"], "categorical")
    xe = {"fieldName": v["x"], "displayName": v["x"], "scale": {"type": xs}}
    ye = {"fieldName": v["y"], "displayName": v["y"], "scale": {"type": "quantitative"}}
    enc = {"x": ye, "y": xe} if v["kind"] == "hbar" else {"x": xe, "y": ye}
    fields = [{"name": v["x"], "expression": f"`{v['x']}`"}, {"name": v["y"], "expression": f"`{v['y']}`"}]
    if v.get("color"):
        enc["color"] = {"fieldName": v["color"], "displayName": v["color"], "scale": {"type": "categorical"}}
        fields.append({"name": v["color"], "expression": f"`{v['color']}`"})
    kind = "line" if v["kind"] == "line" else "bar"
    return widget("w_" + v["name"], v["name"], fields,
                  {"version": 3, "widgetType": kind, "encodings": enc, "frame": {"showTitle": True, "title": v["title"]}}, pos)


def dashboard():
    S = f"{CATALOG}.{SCHEMA}."
    datasets = [{"name": "kpi", "displayName": "Headline KPIs", "queryLines": [P.DASH_KPI_SQL.format(S=S)]}]
    datasets += [{"name": v["name"], "displayName": v["title"], "queryLines": [v["sql"].format(S=S)]} for v in P.VIZ]
    layout = [{"widget": {"name": "title", "multilineTextboxSpec": {"lines": [f"## {P.DASH_TITLE} (full data)"]}}, "position": {"x": 0, "y": 0, "width": 6, "height": 1}}]
    for i, (col, title, fmt) in enumerate(P.COUNTERS):
        layout.append(widget(f"kpi_{col}", "kpi", [{"name": col, "expression": f"`{col}`"}],
                             {"version": 2, "widgetType": "counter", "encodings": {"value": {"fieldName": col, "displayName": title, "format": FMT[fmt]}},
                              "frame": {"showTitle": True, "title": title}}, {"x": i * 2, "y": 1, "width": 2, "height": 2}))
    layout.append({"widget": {"name": "note", "multilineTextboxSpec": {"lines": [P.DASH_NOTE]}}, "position": {"x": 2 * len(P.COUNTERS), "y": 1, "width": 6 - 2 * len(P.COUNTERS), "height": 2}})
    for i, v in enumerate(P.VIZ):
        layout.append(viz_widget(v, {"x": (i % 2) * 3, "y": 3 + (i // 2) * 6, "width": 3, "height": 6}))
    return {"datasets": datasets, "pages": [{"name": "overview", "displayName": "Overview", "pageType": "PAGE_TYPE_CANVAS", "layout": layout}]}


if __name__ == "__main__":
    out = ROOT / "databricks"; out.mkdir(exist_ok=True)
    (out / f"{P.NOTEBOOK}.sql").write_text(notebook())
    (out / f"{P.DASH_FILE}.lvdash.json").write_text(json.dumps(dashboard(), indent=1) + "\n")
    print("wrote", sorted(p.name for p in out.iterdir()))
